### ISSUE TITLE
Add tests section as part of software invocation

### ISSUE THREAD

**Issue by dgarijo** [SoftwareUnderstanding/code_inspector#155]
Right now they are ignored, and they are not annotated.

**Comment by rosafilgueira** [comment]
Example of a test file that is not currently detected as a test: 
[Chowlk/tests/test_finding.py ](https://github.com/oeg-upm/Chowlk/blob/webservice/tests/test_finding.py)

Note: In the latest "test" classification, we removed the use of the file_name ( e.g. that contains "test" in the filename). 

We should ( in the [test classification](https://github.com/SoftwareUnderstanding/code_inspector/blob/main/code_inspector.py#L290)) check if the file has "unnitest" (or other test libraries, e.g. "doctest") inside the dependencies.  Right now,  "unittest" and "doctest" (they might be more test libraries) are only checked if they are included as strings inside the main_function (e.g. unnitest.main()). 

<img width="845" alt="Screen Shot 2021-07-13 at 19 38 53" src="https://user-images.githubusercontent.com/6940078/125507148-fdd5cb33-8e9a-4407-9112-8620e481a52f.png">

**Comment by rosafilgueira** [comment]
I've followed my own advice and now we check the [dependencies list ](https://github.com/SoftwareUnderstanding/code_inspector/blob/main/code_inspector.py#L298), since I needed for doing more tests.  

NOTE: This test classification will need further investigation - this is just a quick improvement from the original implementation. 

Regarding with Chowlk - now it does the expected behaviour. 

<img width="996" alt="Screen Shot 2021-07-14 at 11 28 05" src="https://user-images.githubusercontent.com/6940078/125607395-1b7f718f-799c-4b2d-ac77-7c4e7e431992.png">

**Comment by dgarijo** [comment]
I have now separated tests as a different category.
In software invocation each element of the list has a unique type.
