### ISSUE TITLE
Error in script without main

### ISSUE THREAD

**Issue by dgarijo** [SoftwareUnderstanding/code_inspector#177]
Repository: tada-web

It correctly tags `app.py` as a service. But then `utils.py` is a script without main, which is odd because it's just a `script without main`. In addition, `app.py` is also tagged as `script without main`. I think there is something wrong here

**Comment by rosafilgueira** [comment]
That is because it detects that it s  service, and continues exploring [further.](https://github.com/SoftwareUnderstanding/code_inspector/blob/main/utils.py#L179) 


However, [it does not find a file with main](https://github.com/SoftwareUnderstanding/code_inspector/blob/main/utils.py#L203), and therefore, it continues further ... and it goes to check the [rest of the files](https://github.com/SoftwareUnderstanding/code_inspector/blob/main/utils.py#L236). 

(Just explaining what is going on )

**Comment by rosafilgueira** [comment]
Addressed following the previous advice. We now only allow to continue exploring files that do not have files in case: 1) MAINS not found or SERVICES not found. If we want to change this behaviour, we just need to modify the following [lines](https://github.com/SoftwareUnderstanding/code_inspector/blob/main/utils.py#L188).

Now, tada-web works as it should: 

<img width="951" alt="Screen Shot 2021-07-14 at 18 14 51" src="https://user-images.githubusercontent.com/6940078/125665206-a12a11ee-3fb6-4e60-ad60-3b03f39c9bed.png">
