### ISSUE TITLE
New dynamic functions yields errors in some files

### ISSUE THREAD

**Issue by dgarijo** [SoftwareUnderstanding/code_inspector#271]
This is the reason why the evaluation decreased. I dealt with this by adding exception handling, but it should be looked at.
Function: 
```
def _dynamic_calls(self, f_args, f_name, dynamic_func, remove_calls, funcs_info, classes_info, store_vars={})
```
Example error: in Chowlk, the file `app.py` was being ignored to a Key Error. Now this is the output:
```
Error when processing dependency: os.path.join
Error when processing dependency: jsonify
```

**Comment by rosafilgueira** [comment]
Fixed the problem - now we have a function that ignores (skips) to check if we have a dynamic call, when we have a call made either to imported function/library/method or when we use a built-in-function. Now it has removed 99% of the ERRORS. 

There is still an ERROR, for [autojump](https://github.com/wting/autojump/blob/master/bin/autojump_data.py). But the problem here, is that we dont detect correctly los imports when they are made using an "if ... else .... "

```
if sys.version_info[0] == 3:
    ifilter = filter
    imap = map
else:
    from itertools import ifilter  # noqa
    from itertools import imap  # noqa
```
Since, we dont detect the "iflter" and "imap" as imports (i will work on this on my way back), we dont skipp those ones, when we check for dynamic calls. 

So, we have to improve the self.dependencies to detect imports when we they are made inside if or if and else.

**Comment by rosafilgueira** [comment]
Fixed! There is not error in autojum :) !

**Comment by dgarijo** [comment]
I will close the issue then
